// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvDXoCOtKbV4NmjcnXerO8NrXao0RSLmQ',
    appId: '1:615307897370:android:43f8fd477e6f447bd47fa3',
    messagingSenderId: '615307897370',
    projectId: 'ejemplo-firebase-4da53',
    storageBucket: 'ejemplo-firebase-4da53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQW2LAK3G2WCidFXj4fTpZlNdb8uMUfUk',
    appId: '1:615307897370:ios:cb23c026ec0b2dc5d47fa3',
    messagingSenderId: '615307897370',
    projectId: 'ejemplo-firebase-4da53',
    storageBucket: 'ejemplo-firebase-4da53.appspot.com',
    androidClientId: '615307897370-89gq42cbiiek7t8c22l25v8nich2um97.apps.googleusercontent.com',
    iosClientId: '615307897370-e01frjmhc08p3b0opil5otbgqfus6d9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.albumBiblio',
  );
}
